syntax = "proto3";

package control_messages;

message add_uart_device_request {
    string device_file = 1;
}

message add_uart_device_response {
    enum Status {
        SUCCESS = 0;
        DEVICE_FILE_DOES_NOT_EXIST = 1;
        DEVICE_ALREADY_EXISTS = 2;
        UNKNOWN_ERROR = 3;
    }
    Status status = 1;
    string device_id = 2;
}

message get_statistics_request {
    string device_id = 1;
}

message get_statistics_response {
    enum Status {
        SUCCESS = 0;
        DEVICE_NOT_FOUND = 1;
        UNKNOWN_ERROR = 2;
    }
    Status status = 1;
    uint64 uptime_seconds = 2;
    uint64 broadcast_sent = 3;
    uint64 broadcast_received = 4;
}

message get_list_of_devices_request {
}

message uart_info {
    string device_file = 1;
}

message basic_device_info {
    string device_id = 1;
    oneof connection_type {
        uart_info uart_info = 2;
    }
}

message get_list_of_devices_response {
    repeated basic_device_info devices = 1;
}

message control_envelope {
    uint32 sequence_number = 1;
    oneof action {
        add_uart_device_request add_uart_device_request = 2;
        add_uart_device_response add_uart_device_response = 3;
        get_statistics_request get_statistics_request = 4;
        get_statistics_response get_statistics_response = 5;
        get_list_of_devices_request get_list_of_devices_request = 6;
        get_list_of_devices_response get_list_of_devices_response = 7;
    }
}
